# Generated by Django 3.2.4 on 2021-06-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Matress', max_length=50)),
                ('rigidity', models.CharField(default='Soft', max_length=50)),
                ('weight', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('typeof', models.CharField(max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='main.good')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='main.good')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(blank=True, upload_to='')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Icons', to='main.good')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.BigIntegerField(blank=True, default=20)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Height', to='main.good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.goodscategory'),
        ),
    ]
