# Generated by Django 3.2.4 on 2021-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='popularity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='good',
            name='quolity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
