# Generated by Django 3.2.4 on 2021-06-24 12:17

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_alter_slides_price_0002_auto_20210621_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, default=''),
        ),
    ]
