# Generated by Django 3.2.4 on 2021-06-24 12:35

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='characters',
            field=djrichtextfield.models.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='good',
            name='feedbacks',
            field=djrichtextfield.models.RichTextField(blank=True, default=''),
        ),
    ]
