# Generated by Django 3.2.4 on 2021-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210625_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
