# Generated by Django 3.2.4 on 2021-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=True),
        ),
    ]
