# Generated by Django 3.2.4 on 2021-06-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0010_auto_20210628_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='session_key',
        ),
        migrations.AddField(
            model_name='customer',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
