# Generated by Django 3.2.4 on 2021-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210628_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='session',
        ),
        migrations.AddField(
            model_name='customer',
            name='session_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
