# Generated by Django 3.2.4 on 2021-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210628_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='for_anonymous_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
