# Generated by Django 3.2.4 on 2021-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210628_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_cart',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='goods_cart',
            name='object_id',
        ),
    ]
