# Generated by Django 3.2.4 on 2021-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_goods_cart_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_cart',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
