# Generated by Django 3.2.4 on 2021-06-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0018_goods_cart_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_cart',
            name='content_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
