# Generated by Django 3.2.4 on 2021-06-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210628_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_cart',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель'),
        ),
    ]
