# Generated by Django 3.2.4 on 2021-06-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210628_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image_for_cart',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
