# Generated by Django 3.2.4 on 2021-06-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_cart',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='goods_cart',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10),
        ),
    ]
