# Generated by Django 3.2.4 on 2021-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210629_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10),
        ),
    ]
