# Generated by Django 3.2.4 on 2021-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210629_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cart', to='main.Goods_Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
