# Generated by Django 3.2.5 on 2021-07-05 06:36

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0028_auto_20210703_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'IP пользователя товара', 'verbose_name_plural': 'IP пользователя товара'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='goods_cart',
            options={'verbose_name': 'Корзина товара', 'verbose_name_plural': 'Корзина товара'},
        ),
        migrations.AlterModelOptions(
            name='goods_height',
            options={'verbose_name': 'Высота товара', 'verbose_name_plural': 'Высота товара'},
        ),
        migrations.AlterModelOptions(
            name='goods_icons',
            options={'verbose_name': 'Иконка товара', 'verbose_name_plural': 'Товара товара'},
        ),
        migrations.AlterModelOptions(
            name='goods_images',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Картинка товара'},
        ),
        migrations.AlterModelOptions(
            name='goods_sizes',
            options={'verbose_name': 'Размер товара', 'verbose_name_plural': 'Размер товара'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': 'Категории товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Слайдеры', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='for_anonymous_users',
            field=models.BooleanField(default=False, verbose_name='Для анонимов'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='Занятая корзина'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.Goods_Cart', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='session_id',
            field=models.GenericIPAddressField(null=True, verbose_name='IP пользователя'),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.goodscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='characters',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='feedbacks',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image_for_cart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка для корзины'),
        ),
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='popularity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quolity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='rigidity',
            field=models.CharField(max_length=50, verbose_name='Жесткость'),
        ),
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.BigIntegerField(verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='goods_cart',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='goods_height',
            name='height',
            field=models.BigIntegerField(blank=True, default=20, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='goods_icons',
            name='icons',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иконки'),
        ),
        migrations.AlterField(
            model_name='goods_images',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='goods_sizes',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='cat',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
