# Generated by Django 3.2.4 on 2021-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.Goods_Cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='session_id',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
