# Generated by Django 3.2.4 on 2021-07-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210703_0629'),
        ('main', '0029_auto_20210701_1418'),
    ]

    operations = [
    ]
