# Generated by Django 3.2.4 on 2021-07-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210705_0936'),
        ('main', '0031_auto_20210703_1837'),
    ]

    operations = [
    ]
