# Generated by Django 3.2.4 on 2021-07-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210705_1814'),
        ('main', '0033_auto_20210705_1514'),
    ]

    operations = [
    ]
