# Generated by Django 3.2.4 on 2021-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_merge_0030_auto_20210705_1814_0033_auto_20210705_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя заказчика')),
                ('telephone', models.IntegerField(max_length=13, null=True, verbose_name='Телефон Заказчика')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Заказчика')),
                ('agreement', models.BooleanField(default=False, verbose_name='Соглашение с правилами')),
                ('products', models.ManyToManyField(blank=True, to='main.Goods_Cart', verbose_name='Товары')),
            ],
        ),
    ]
